---

vs_name: "hello30"
vs_ip: "10.1.10.30"
vs_port: "80"
vs_snat: "Automap"
pl_name: "app1_pool"
pl_monitor: "/Common/http"
pl_lb: "round-robin"
nd_qty: "2"
nd_port: "80"
nd_ip1: 10.1.20.15
nd_ip2: 10.1.20.16
